# Generated by Django 6.1.2 on 2026-10-06 16:28

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(max_length=64, unique=True)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('rank', models.CharField(blank=True, max_length=120)),
                ('organization', models.CharField(blank=True, default='Anti-Corruption Corps', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['badge_id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=core.models.public_id_default, max_length=16, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=8000)),
                ('category', models.CharField(choices=[('bribery', 'Bribery / Kickbacks'), ('embezzlement', 'Embezzlement / Misuse of Funds'), ('abuse', 'Abuse of Power'), ('fraud', 'Fraud / Forgery'), ('procurement', 'Rigged Procurement / Contracts'), ('electoral', 'Electoral Misconduct'), ('violence', 'Threats / Violence / Intimidation'), ('other', 'Other Corruption / Crime')], default='other', max_length=24)),
                ('location_text', models.CharField(help_text='Area / landmark. Never include your name or address.', max_length=200)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('happened_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Justice'), ('investigating', 'Justice in Motion'), ('resolved', 'Resolved & Verified')], db_index=True, default='pending', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_message', models.TextField(blank=True, max_length=4000)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, help_text='Reports go live immediately.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(max_length=255, upload_to=core.models.evidence_upload_to)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_resolution', models.BooleanField(default=False, help_text='Officer-supplied proof of resolution.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.report')),
            ],
            options={
                'ordering': ['is_resolution', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='core_report_status_2f6592_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['category', '-created_at'], name='core_report_categor_af59d2_idx'),
        ),
    ]
