# Generated by Django 6.1.2 on 2026-10-06 16:36

import core.models
import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportevidence',
            name='file',
            field=models.FileField(max_length=255, storage=core.storages.ConfiguredEvidenceStorage(), upload_to=core.models.evidence_upload_to),
        ),
    ]
