# Generated by Django 6.1.2 on 2026-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reportevidence_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='headline', help_text='Stable id, e.g. headline.', unique=True)),
                ('message', models.CharField(help_text='One line. Plain words — shown under the nav on every page.', max_length=240)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('urgent', 'Urgent')], default='info', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only active notices can show.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lowest order wins when several are active.')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Optional: show from this time.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Optional: hide after this time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-updated_at'],
            },
        ),
    ]
