# Generated by Django 6.1.2 on 2026-10-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevidence',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportevidence',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
