# Generated by Django 6.1.2 on 2026-10-06 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Public alias only.', max_length=60, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated, e.g. forensics, malware analysis', max_length=255)),
                ('services', models.TextField(blank=True, max_length=2000)),
                ('price_range', models.CharField(blank=True, help_text='e.g. NPR 5,000–25,000 / case', max_length=80)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='guardians/%Y/')),
                ('relay_handle', models.CharField(blank=True, help_text='Masked relay ID shown publicly, e.g. relay-7f3a. Never a personal handle.', max_length=80)),
                ('affiliated_org', models.CharField(blank=True, max_length=160)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Set only after cops / affiliated org verify identity.')),
                ('is_listed', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('private_identity_ref', models.TextField(blank=True, help_text='Real identity dossier reference. Staff-only. Never rendered publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=140)),
                ('message', models.TextField(help_text='Describe the help you need. Do NOT include your real name.', max_length=2000)),
                ('callback', models.CharField(blank=True, help_text='Optional throwaway relay where the team can reach you.', max_length=140)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed by team'), ('connected', 'Connected via relay')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='marketplace.hackerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HackerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Team member authoring the rating.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='marketplace.hackerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
